### ISSUE TITLE
recipe for target 'logitech_install' failed

### ISSUE THREAD

**Issue by AlmightyFrog** [BastilleResearch/nrf-research-firmware#12]
I've got an old
`Bus 001 Device 033: ID 046d:c52b Logitech, Inc. Unifying Receiver`
dongle which i want to flash.
For this reason i am building a docker container.
Sadly it does stop with following error:

> ./prog/usb-flasher/logitech-usb-flash.py bin/dongle.formatted.bin bin/dongle.formatted.ihx
[2017-11-13 17:59:57.604]  Computing the CRC of the firmware image
[2017-11-13 17:59:57.649]  Preparing USB payloads
[2017-11-13 17:59:57.716]  Found Logitech Unifying dongle - HID mode
[2017-11-13 17:59:57.716]  Detaching kernel driver from Logitech dongle - HID mode
Traceback (most recent call last):
  File "./prog/usb-flasher/logitech-usb-flash.py", line 42, in <module>
    dongle = unifying_dongle()
  File "/data/mousejack/nrf-research-firmware/prog/usb-flasher/unifying.py", line 56, in __init__
    if self.dongle.is_kernel_driver_active(ep):
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1061, in is_kernel_driver_active
    self._ctx.managed_open()
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)
make: *** [logitech_install] Error 1
Makefile:33: recipe for target 'logitech_install' failed
The command '/bin/sh -c make logitech_install' returned a non-zero code: 2

Any Idea what goes wrong here? Base image is current debian stretch.

Here the Docker file so far
> FROM debian:stretch
> 
> RUN apt-get update && \
    apt-get -y --no-install-recommends install sdcc binutils python python-pip make git libusb-1.0-0 && \
    apt-get -y -u dist-upgrade && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN pip2 install -U pip setuptools wheel
RUN pip2 install -U -I pyusb
RUN pip2 install -U platformio
RUN mkdir -p /data/mousejack/
WORKDIR /data/mousejack/
RUN git clone --depth=1 https://github.com/BastilleResearch/mousejack .
RUN git submodule init
RUN git submodule update
WORKDIR /data/mousejack/nrf-research-firmware
RUN make
RUN make logitech_install

**Comment by AlmightyFrog** [comment]
Ok, found it myself. Was a combination with timing and in first place forget to mount /lib/modules/ into container. Now it worked:
$ docker run --privileged --cap-add=ALL -v /lib/modules:/lib/modules -it mousejack:latest
