### ISSUE TITLE
Logitech Unifying different usb id

### ISSUE THREAD

**Issue by Zibri** [BastilleResearch/nrf-research-firmware#17]
I have logitech mouse G700s.
lsusb says:
Bus 001 Device 075: ID 046d:c531 Logitech, Inc. C-U0007 [Unifying Receiver]

I modified the usb id in unifying.py
And I tried to dump the firmware.

But I get:

sudo python2 prog/usb-flasher/logitech-usb-backup.py firmware-backup.bin infopage.bin
[2019-01-17 20:54:00.392]  Found Logitech Unifying dongle - HID mode
[2019-01-17 20:54:00.392]  Detaching kernel driver from Logitech dongle - HID mode
[2019-01-17 20:54:00.557]  Putting dongle into firmware update mode
Traceback (most recent call last):
  File "prog/usb-flasher/logitech-usb-backup.py", line 19, in <module>
    dongle = unifying_dongle()
  File "/home/zibri/nrf-research-firmware/prog/usb-flasher/unifying.py", line 63, in __init__
    self.enter_firmware_update_mode()
  File "/home/zibri/nrf-research-firmware/prog/usb-flasher/unifying.py", line 135, in enter_firmware_update_mode
    response = self.send_command(0x21, 0x09, 0x0210, 0x0002, "\x10\xFF\x81\xF1\x01\x00\x00", ep=0x83)
  File "/home/zibri/nrf-research-firmware/prog/usb-flasher/unifying.py", line 179, in send_command
    ret = self.dongle.ctrl_transfer(request_type, request, value, index, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1034, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found

**Comment by Zibri** [comment]
[812047.995334] usb 1-3: USB disconnect, device number 82
[812049.983070] usb 1-3: new full-speed USB device number 83 using xhci_hcd
[812050.133590] usb 1-3: New USB device found, idVendor=046d, idProduct=c531, bcdDevice=21.00
[812050.133597] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[812050.133600] usb 1-3: Product: USB Receiver
[812050.133604] usb 1-3: Manufacturer: Logitech

**Comment by Zibri** [comment]
lsusb also reports: 
```
  iManufacturer           1 Logitech
  iProduct                2 USB Receiver
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           59
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          4 RQR21.00_B0007
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               98mA

```

**Comment by DRCRecoveryData** [comment]
> lsusb also reports:
> 
> ```
>   iManufacturer           1 Logitech
>   iProduct                2 USB Receiver
>   iSerial                 0 
>   bNumConfigurations      1
>   Configuration Descriptor:
>     bLength                 9
>     bDescriptorType         2
>     wTotalLength           59
>     bNumInterfaces          2
>     bConfigurationValue     1
>     iConfiguration          4 RQR21.00_B0007
>     bmAttributes         0xa0
>       (Bus Powered)
>       Remote Wakeup
>     MaxPower               98mA
> ```

you need flash new bootloader to it
