### ISSUE TITLE
usb-flash still depends on Python2

### ISSUE THREAD

**Issue by chadmiller** [BastilleResearch/nrf-research-firmware#20]
Python 2 is almost dead. Python3 has been around forever and should be the default.

**Comment by Decapitater** [comment]
hi can you help me solve 
No Module named usb 

`./prog/usb-flasher/logitech-usb-flash.py bin/dongle.formatted.bin bin/dongle.formatted.ihx
Traceback (most recent call last):
  File "./prog/usb-flasher/logitech-usb-flash.py", line 3, in <module>
    from unifying import *
  File "/home/zodiac/Downloads/nrf-research-firmware/prog/usb-flasher/unifying.py", line 19, in <module>
    import usb, logging, time, sys, struct, os
ImportError: No module named usb
make: *** [Makefile:33: logitech_install] Error 1`

**Comment by TheRealMephisto** [comment]
@Decapitater Did you use the code adjustments from @chadmiller ?

Try changing "python3" to "python" in the first line of usb-flash.py, seems to be a wrong reference to the usb module when using python3

**Comment by TheRealMephisto** [comment]
Nevermind, there was still a reference to pyusb from a python2 library on my machine - got confused. 
I am still running in the same issue as @Decapitater , will continue looking for a fix.
