### ISSUE TITLE
Resource busy

### ISSUE THREAD

**Issue by rafaferreirasantos** [BastilleResearch/nrf-research-firmware#23]
Hi, I'm trying to downgrade my Unifying dongle with logitech-usb-restore and a VirtualMachine but I'm getting this error:
![image](https://user-images.githubusercontent.com/7022211/75465872-06932980-5968-11ea-9316-0aea8da64bec.png)

Could someone help me?
Thank you.

**Comment by TheRealMephisto** [comment]
@rafaferreirasantos  Did you ever come up with a fix?

**Comment by rafaferreirasantos** [comment]
No.. I couldn't downgrade. I ended up buying another device.

**Comment by TheRealMephisto** [comment]
I figure that the resource needs to be released by the command 
`usb.util.dispose_resources(self.dongle)` 
which I've added as the first line in the definition of the function send_command in the unifying.py script.

At least this let me proceed with the flashing of the logitech unifying dongle. Still end up in an error though:

> [2023-05-18 23:19:56.103]  Mark firmware update as completed
[2023-05-18 23:19:56.489]  20:00:00:01:02:6B:32:FF:FF:FF:FF:FF:FF:FF:32:FF:FF:FF:FF:FF:DC:D8:E3:7F:35:C0:42:A2:EE:ED:03:A3
[2023-05-18 23:19:56.491]  Restarting dongle into research firmware mode
Traceback (most recent call last):
  File "./prog/usb-flasher/logitech-usb-flash.py", line 65, in <module>
    response = dongle.send_command(0x21, 0x09, 0x0200, 0x0000, "\x70" + "\x00"*31)
  File "/home/mephisto/Software/mousejack-dockerized/mousejack/nrf-research-firmware/prog/usb-flasher/unifying.py", line 180, in send_command
    response = self.dongle.read(ep, 32, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1022, in read
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 869, in intr_read
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error
Makefile:33: recipe for target 'logitech_install' failed
make: *** [logitech_install] Error 1
