### ISSUE TITLE
New Instructions?

### ISSUE THREAD

**Issue by Brumbpo-Tungus** [BastilleResearch/nrf-research-firmware#27]
Hello,
I would like to flash my Logitech dongle, I am just struggling to install the firmware, as I believe some of the commands are old and based on python 2.7? I am using Ubuntu 20.04. Could someone please help me install on this distribution?

**Comment by Brumbpo-Tungus** [comment]
Ok so raspbian works ok, it still have 2.7 python. But I get this right at the end :

[2021-03-02 05:05:31.626]  20:00:00:01:02:6B:32:FF:FF:FF:FF:FF:FF:FF:32:FF:FF:FF:FF:FF:37:15:3F:DF:18:0D:9C:0C:EF:E5:C3:7B
[2021-03-02 05:05:31.629]  Restarting dongle into research firmware mode
Traceback (most recent call last):
  File "./prog/usb-flasher/logitech-usb-flash.py", line 65, in <module>
    response = dongle.send_command(0x21, 0x09, 0x0200, 0x0000, "\x70" + "\x00"*31)
  File "/home/pi/nrf-research-firmware/prog/usb-flasher/unifying.py", line 180, in send_command
    response = self.dongle.read(ep, 32, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1024, in read
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 869, in intr_read
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)
make: *** [Makefile:33: logitech_install] Error 1

So not sure if its flashed correctly or not?

**Comment by Brumbpo-Tungus** [comment]
So it works in Bettercap, I just can't inject into my logitech BT keyboard - but scans ok etc. 
My advice to anyone trying this, use the Raspberry Pi CLI image, on a VM maybe, or just an RPi, as the instructions listed work fine with it.
