### ISSUE TITLE
usb.error pipe

### ISSUE THREAD

**Issue by ghost** [BastilleResearch/nrf-research-firmware#37]
Hello

I have issue flashing firmware to CrazyRadio 2.0
After identifying device usb-flash.py script gives an error
Would appreciate any ideas or suggestions

user@user-VirtualBox:/opt/mousejack/nrf-research-firmware$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 003: ID 1915:7777 Nordic Semiconductor ASA 
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
user@user-VirtualBox:/opt/mousejack/nrf-research-firmware$ sudo make install
[sudo] password for user: 
./prog/usb-flasher/usb-flash.py bin/dongle.bin
[2023-10-03 07:52:13.178]  Looking for a compatible device that can jump to the Nordic bootloader
[2023-10-03 07:52:13.224]  Device found, jumping to the Nordic bootloader
Traceback (most recent call last):
  File "./prog/usb-flasher/usb-flash.py", line 70, in <module>
    else: dongle.ctrl_transfer(0x40, 0xFF, 0, 0, (), timeout=usb_timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1079, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 901, in ctrl_transfer
    timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
Makefile:27: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by Oreldm** [comment]
Same here, tried on 2 different computers for hours (with tons of workaround). It seems the moment I tried sending 0x40 (for example dongle.ctrl_transfer(0x40, 0xFF, 0, 0, (), timeout=usb_timeout) ) it didn't work. Also I tried many other protocols, but it just doesn't seems to work.
If someone know what is the problem with Crazy Radio PA 2.0 and how to flash it, it can help
Thanks!

**Comment by XtramCZ** [comment]
This issue also happens with the Logitech unifying dongle
