### ISSUE TITLE
sudo make install issue

### ISSUE THREAD

**Issue by kobra666** [BastilleResearch/nrf-research-firmware#39]
sudo make install
./prog/usb-flasher/usb-flash.py bin/dongle.bin
Traceback (most recent call last):
  File "./prog/usb-flasher/usb-flash.py", line 20, in <module>
    import usb, time, sys, array, logging
ImportError: No module named usb
make: *** [Makefile:27: install] Error 1

I tried pip install pyusb..but still the same.. please help me how to fix this guys

**Comment by kobra666** [comment]
I finally found a solution. purge the whole python2.7 and everything. and reinstall it. and I changed shebangs in scripts to python2.7 and its working now!.

**Comment by HeroNootRoot** [comment]
can u help me with that i didnt understand
it shows me "
┌──(root㉿cyber)-[/nrf-research-firmware]
└─# sudo make install                                        
./prog/usb-flasher/usb-flash.py bin/dongle.bin
Traceback (most recent call last):
  File "./prog/usb-flasher/usb-flash.py", line 20, in <module>
    import usb, time, sys, array, logging
ImportError: No module named usb
make: *** [Makefile:27: install] Error 1

 "

**Comment by kobra666** [comment]
try what I did, find out which version of python2 are you using.mine was 2.7.  now go to nrf/prog/usbflasher/usbflash.py  open it with text editor and change the first line #!/usr/bin/env python2    to #!/usr/bin/env python2.7    it worked for me

**Comment by HeroNootRoot** [comment]
i did it and it kinda worked but now shows me another error 
"
┌──(root㉿cyber)-[/nrf-research-firmware]
└─# sudo make install        
./prog/usb-flasher/usb-flash.py ./bin/dongle.bin
make: ./prog/usb-flasher/usb-flash.py: No such file or directory
make: *** [Makefile:27: install] Error 127"

even though the file does exist and im trying to do mousejacking on my other pc but i dont understand why its not working and i cant find RFStorm Firmware and im not sure crazyradio firmware will work for that and i also dont know what else i need to fix this things

**Comment by kobra666** [comment]
yes I got same error, but I solved it somehow, but it was long time ago and I dont remember how I did it, I'm tryin to find some old screenshots of this issue and how to solve it

**Comment by kobra666** [comment]
do you have all requirements installed? sdcc pyusb binutils ?

**Comment by kobra666** [comment]
Copyright (C) 2016 Bastille Networks

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or

(kali@HP-DeskJetPlus) ~/mousejack/nrf-research-firmware
File Actions Edit View Help

$ sudo make install
/prog/usb-flasher/usb-flash.py bin/dongle.bin
/bin/env: ‘python2’: No such file or directory
make: *** [Makefile:27: install] Error 127

(kali@HP-DeskJetPlus) ~/mousejack/nrf-research-firmware
$ python2 --version
Python 2.7.18

(kali@HP-DeskJetPlus) ~/mousejack/nrf-research-firmware
$ sudo make install
/prog/usb-flasher/usb-flash.py bin/dongle.bin
[2024-05-30 22:18:15.824] Looking for a compatible device that can jump to the Nordic bootloader
[2024-05-30 22:18:15.851] Looking for a device running the Nordic bootloader
Traceback (most recent call last):
  File "usb-flash.py", line 92, in <module>
    raise Exception("No compatible device found.")
Exception: No compatible device found.
make: *** [Makefile:27: install] Error 1

(kali@HP-DeskJetPlus) ~/mousejack/nrf-research-firmware
$ sudo make install
/prog/usb-flasher/usb-flash.py bin/dongle.bin
[2024-05-30 22:19:03.056] Looking for a compatible device that can jump to the Nordic bootloader
[2024-05-30 22:19:03.085] Device found, jumping to the Nordic bootloader
[2024-05-30 22:19:03.489] Looking for a device running the Nordic bootloader
[2024-05-30 22:19:03.781] Writing image to flash
[2024-05-30 22:19:04.101] Verifying write
[2024-05-30 22:19:04.501] Firmware programming completed successfully
Please unplug your dongle or breakout board and plug it back in.

(kali@HP-DeskJetPlus) ~/mousejack/nrf-research-firmware
$
``



----------after error 127 I only changed the shebang to my actual python version,then it worked

**Comment by kobra666** [comment]
gpt advice:

To fix the Error 127, your friend should follow these steps:

1. Verify the script file exists
Run:

bash
ls -l ./prog/usb-flasher/usb-flash.py
If the file doesn’t exist, they might be in the wrong directory. Navigate to the correct one using:

bash
cd /path/to/nrf-research-firmware

2. Check and fix file permissions
If the file exists but isn’t executable, run:

bash
chmod +x ./prog/usb-flasher/usb-flash.py

3. Ensure Python 2.7.18 is installed
Check if Python 2 is installed:

bash
python2 --version

4. Fix the shebang in the script
Open usb-flash.py:

bash
nano ./prog/usb-flasher/usb-flash.py
Make sure the first line is:

bash
#!/usr/bin/env python2.7.18

5. (Optional) Create a symlink for python2
If step 4 works, but they want a permanent fix, they can link Python 2.7.18 to python2:

bash
sudo ln -sf /usr/bin/python2.7 /usr/bin/python2

Now #!/usr/bin/env python2 will work properly for all scripts.

6. Try running the install command again
bash
sudo make install

**Comment by HeroNootRoot** [comment]
it didnt work. are u did mousejacking too? maybe u got rfstorm firmware by any chance after i will fix this current problem

**Comment by kobra666** [comment]
of course.but i used only nrf research firmware. you are not far from solution. I remember it took my over a week to get this running but its possible.

**Comment by HeroNootRoot** [comment]
btw do i need to install crazyradio firmware if i want to do mousejacking on my other pc?

**Comment by kobra666** [comment]
w8 i think crazyradio dongle has crazyradio firmware on it, and you need to patch it with nrf reserach firmware to do mouse jacking, thats way I did it

**Comment by HeroNootRoot** [comment]
u got discord by any chance?

**Comment by kobra666** [comment]
nope telegram only

**Comment by HeroNootRoot** [comment]
alr

**Comment by HeroNootRoot** [comment]
how do i add u?
